#!/usr/bin/env python3
"""شهاب — mobile type floor.

Scans the page and component sheets for every selector whose font-size is
below 12px and appends one block to css/responsive.css that raises them to
12px on phones (≤640px). Icons (.sh-i) and decorative marks are skipped.
Idempotent: the block between the markers is regenerated on each run.

Usage:  python tools/a11y.py
"""
import os, re, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

START = '/* == sh:type-floor == */'
END = '/* == /sh:type-floor == */'
SHEETS = ['css/components.css', 'css/header.css', 'css/footer.css', 'css/widgets.css', 'css/brief.css',
          'css/player.css', 'css/gallery.css'] + sorted(glob.glob('css/pages/*.css'))
SKIP = re.compile(r'\.sh-i\b|__i-\d|sh-fs-\d|\bi\b|::|:before|:after|sh-mark|__num|__no\b|keyframes')


def small_selectors():
    out = []
    for f in SHEETS:
        css = open(f, encoding='utf-8').read()
        css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
        for m in re.finditer(r'([^{}]+)\{([^{}]*)\}', css):
            sel, body = m.group(1).strip(), m.group(2)
            fs = re.search(r'(?:^|;)\s*font-size\s*:\s*([0-9.]+)px', body)
            if not fs or float(fs.group(1)) >= 12:
                continue
            if sel.startswith('@') or '@media' in sel:
                continue
            for part in sel.split(','):
                part = part.strip()
                if not part or SKIP.search(part):
                    continue
                out.append(part)
    seen, uniq = set(), []
    for s in out:
        if s not in seen:
            seen.add(s); uniq.append(s)
    return uniq


if __name__ == '__main__':
    sels = small_selectors()
    block = (START + '\n/* generated by tools/a11y.py: nothing below 12px on phones (%d selectors) */\n'
             '@media (max-width:640px){\n  @layer responsive{\n    %s{font-size:12px!important}\n  }\n}\n' + END) % (len(sels), ',\n    '.join(sels))
    p = 'css/responsive.css'
    s = open(p, encoding='utf-8').read()
    if START in s:
        s = re.sub(re.escape(START) + r'.*?' + re.escape(END), lambda m: block, s, flags=re.S)
    else:
        s = s.rstrip() + '\n\n' + block + '\n'
    open(p, 'w', encoding='utf-8', newline='\n').write(s)
    print('type floor:', len(sels), 'selectors')
